CREATE DATABASE admin_db;
CREATE DATABASE user_db;
CREATE DATABASE order_db;
CREATE DATABASE inventory_db;
CREATE DATABASE seller_db;
CREATE DATABASE payment_db;
CREATE DATABASE product_db;
CREATE DATABASE shipping_db;
