spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Kr12@984872
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Kr12@984872
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8081
