spring:
  application:
    name: sellerservice
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ramcharan8@
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ramcharan8@
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8081