spring:
  application:
    name: orderservice

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Kr12@984872

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
